### ISSUE TITLE
How to audit create and drop SQL?

### ISSUE THREAD

**Issue by william0106** [mcafee-enterprise/mysql-audit#241]
My test results:
If audit_ record_ CMDS = '', create and drop SQL can be audited.
But audit_ record_ cmds='insert,delete,update,create,drop,alter,grant,truncate'; Create and drop SQL will not be recorded in the log.

My problem: How to audit create and drop SQL when using audit_ record_ cmds?

**Comment by loveylh** [comment]
我也遇到了这个问题，如果用audit_record_CMDS = ''形式，会把所有语句都记录下来audit_record_cmds='insert,delete,update,create,drop,alter,grant,truncate'，又无法记录create、drop、alter等语句，有好的解决方案吗

**Comment by loveylh** [comment]
> 我也遇到了这个问题，如果用audit_record_CMDS = ''形式，会把所有语句都记录下来audit_record_cmds='insert,delete,update,create,drop,alter,grant,truncate'，又无法记录create、drop、alter等语句，有好的解决方案吗

我已经解决了，实际上create、drop和alter的筛选，是需要修改为create_table，drop_table，alter_table形式，只有这种模式，才会进行记录

**Comment by loveylh** [comment]
> 我也遇到了这个问题，如果用audit_record_CMDS = ''形式，会把所有语句都记录下来audit_record_cmds='insert,delete,update,create,drop,alter,grant,truncate'，又无法记录create、drop、alter等语句，有好的解决方案吗

我已经解决了，实际上create、drop和alter的筛选，是需要修改为create_table，drop_table，alter_table形式，只有这种模式，才会进行记录

**Comment by william0106** [comment]
> > 我也遇到了这个问题，如果用audit_record_CMDS = ''形式，会把所有语句都记录下来audit_record_cmds='insert,delete,update,create,drop,alter,grant,truncate'，又无法记录create、drop、alter等语句，有好的解决方案吗
> 
> 我已经解决了，实际上create、drop和alter的筛选，是需要修改为create_table，drop_table，alter_table形式，只有这种模式，才会进行记录

已测，确定可用。
感谢分享。
当初我也怀疑是参数格式的问题，奈何在相关资料中没找到。
另外我有个建议：既然是开源软件，create_table、drop_table、alter_table改为create、drop、alter，岂不更好理解，更不容易犯错？

**Comment by loveylh** [comment]
> > > 我也遇到了这个问题，如果用audit_record_CMDS = ''形式，会把所有语句都记录下来audit_record_cmds='insert,delete,update,create,drop,alter,grant,truncate'，又无法记录create、drop、alter等语句，有好的解决方案吗
> > 
> > 
> > 我已经解决了，实际上create、drop和alter的筛选，是需要修改为create_table，drop_table，alter_table形式，只有这种模式，才会进行记录
> 
> 已测，确定可用。 感谢分享。 当初我也怀疑是参数格式的问题，奈何在相关资料中没找到。 另外我有个建议：既然是开源软件，create_table、drop_table、alter_table改为create、drop、alter，岂不更好理解，更不容易犯错？老外的思维不可理解。

我是通过audit_whitelist_cmds参数解决的，这个参数可以设置哪些sql操作不被记录，然后通过日志文件猜出是格式问题，可能是因为update等只是动了表数据，而alter这种修改了表结构，所以命名不同

**Comment by william0106** [comment]
The problem has been solved.
